#map_frame: coverage_map
#coverage_frame: robot_0/base_footprint

# Rate at which progress tracker should be run
rate: 20.0  # Hz

grid:
  width: 50.0
  height: 50.0
  resolution: 0.05
  origin:
    x: -25.0
    y: -25.0

coverage:
  # NOTE: To compensate for discretization, radius will be incremented further by 2*resolution
  # internally. Specify the radius accordingly.
  radius: 0.10
  # How effective cleaning in each timestep is
  effectivity: 0.75
