obstacle_range: 3.0
raytrace_range: 3.5

footprint: [[-0.205, -0.155], [-0.205, 0.155], [0.077, 0.155], [0.077, -0.155]]

obstacle_layer:
  observation_sources: scan
  scan:
    {
      sensor_frame: base_scan,
      data_type: LaserScan,
      topic: scan,
      marking: true,
      clearing: true,
    }

inflation_layer:
  inflation_radius: 1.0
  cost_scaling_factor: 3.0
